### Humidor Climate Sensors ########################################
sensor:
  - platform: dht
    pin: "${Pin_DHT_sensor}"
    temperature:
      name: "${device_namelabel} Temperature"
    humidity:
      name: "${device_namelabel} Humidity"
      id: humidity
      accuracy_decimals: 1
    update_interval: 3s