### Device Basic Configuration ################################################
### Device Template 1.0
substitutions:
  devicename: "esphome-fireplace"
  friendly_devicename: "ESP Fireplace"
#these must be set correctly on adoption
esp8266:
  board: esp01_1m 
###
### END

### Common ESPHome Device Configurations ################################################
### No or few changes should be needed
#
esphome:
  name: ${devicename}
  friendly_name: ${friendly_devicename}
  min_version: 2024.11.0
  name_add_mac_suffix: false
# Enable logging
logger:
# Enable Home Assistant API and encryption key
api:
  encryption: 
    key: !secret API_key
# Enable Over The Air updates with ESPhome
ota:
  platform: esphome
# Enable Wifi commented lines are for moving between networks
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  use_address: ${devicename}.local
#  use_address: 10.0.20.140
#
# Enable fallback hotspot & captive portal in case wifi connection fails >1 minute
  ap:
    ssid: ${devicename}
    password: !secret ESPadmin_password
captive_portal:

### Common Diagnostic Display Configuration ################################################
# Adds Diagnostics to HA
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_devicename}: IP"
      icon: "mdi:ip-outline"
    mac_address:
      name: "${friendly_devicename}: MAC"
      icon: "mdi:network-outline"
    ssid:
      name: "${friendly_devicename}: SSID"
      icon: "mdi:wifi-settings"      
sensor:
  - platform: wifi_signal
    name: "${friendly_devicename}: WiFi Signal"
    update_interval: 60s
# Restart & Safe Mode Buttons to HA
button:
  - platform: restart
    name: "Restart Device"
  - platform: safe_mode
    name: "Restart in Safe Mode"

### Custom Device Configuration ################################################

# Green LED Status indicator
  # Solid = powered, normal function
  # Slow Blink = Warning in logs
  # Fast Blink = Error in logs
status_led:
    id: onboard_led
    pin: GPIO13 
#      number: GPIO13 

switch:
# Milivolt circuit relay and Red LED indicator
  - platform: gpio
    pin: GPIO12
    id: relay
    icon: "mdi:fireplace"
    name: "Fireplace"
    restore_mode: ALWAYS_OFF

### Sensor for active wall switch state  
binary_sensor:
  - platform: gpio
    id: wall
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "Wall Switch"
    on_state:
      then:
        - switch.toggle: relay