################################################################################
### WARNING Core Configuration Settings: confirm before adoption ###############
esp8266:
  board: esp01_1m 
### Core Template 2.0
packages:
  template: !include
    file: common/core-template.yaml
    vars:
### WARNING Template Substitutions: adjust during setup ########################
      devicename: "esphome-fireplace"       #used as mDNS name
      friendly_devicename: "ESP Fireplace"  #used in ESP Manager & HA Device
      device_ip_address: "10.0.20.140"  #must be DHCP reserved. For wifi settings changes / mDNS failures
### Troubleshooting wifi: Remove commments to override template
#wifi:
#  use_address: ${devicename}.local
#  use_address: ${device_ip_address} #set in Template Substitutions above
###
substitutions:
### WARNING Naming Substituion: Adjust during setup ############################
  device_namelabel: "Fireplace"
### END Core Template
################################################################################
###
### Device Specific Substitutions ##############################################
# Wiring Substitution
  # Header pin for GND/TX/RX/3v3 for initial flash: not connected
  # Out+ and Out- mounting holes: Relay fireplace side. Soldier to 2x fireplace leads, polarity doesn't matter.
  # In+ and In- mounting holes: Relay null loop. Soldier together.
  # 5~24+ Pin: Red from 5v USB charger
  # 5~24- Pin: White from 5v USB charger
  Onboard_Relay: "GPIO12"    # Red LED
  Onboard_LED: "GPIO13"   #Green LED
  Pin_Wall_Switch: "GPIO14" # Pins IO14-S and IO14-G: Wall Switch, polarity doesn't matter.
###
### Custom Device Configuration ################################################
###
### Green LED Status indicator #####################################
# Solid = powered, normal function
# Slow Blink = Warning in logs
# Fast Blink = Error in logs
status_led:
    id: onboard_led
    pin: ${Onboard_LED}
#
### Relay for Milivolt circuit #####################################
# NOTE: defaults to off on reboot/power restore
# Red LED indicator
switch:
  - platform: gpio
    id: relay
    name: "Fireplace"
    pin: ${Onboard_Relay}
    icon: "mdi:fireplace"
    restore_mode: ALWAYS_OFF
#
### Sensor for wall switch state ###################################
# Toggles the milivolt relay
binary_sensor:
  - platform: gpio
    name: "Wall Switch"
    pin:
      number: ${Pin_Wall_Switch}
      mode: INPUT_PULLUP
      inverted: True
    on_state:
      then:
        - switch.toggle: relay