################################################################################
### WARNING Core Configuration Settings: confirm before adoption ###############
esp32:
  board: esp32dev
  framework:
    type: esp-idf
### Core Template 2.0
packages:
  template: !include
    file: common/core-template.yaml
    vars:
### WARNING Template Substitutions: adjust during setup ########################
      devicename: "esphome-ro"       #used as mDNS name
      friendly_devicename: "ESP RO"  #used in ESP Manager & HA Device
      device_ip_address: "10.0.20.111"  #must be DHCP reserved. For wifi settings changes / mDNS failures
### Troubleshooting wifi: Remove commments to override template
#wifi:
#  use_address: ${devicename}.local
#  use_address: ${device_ip_address} #set in Template Substitutions above
###
substitutions:
### WARNING Naming Substituion: Adjust during setup ############################
  device_namelabel: "RO"
### END Core Template
################################################################################
###
### Device Specific Substitutions ##############################################
# Wiring Substitution
  # Pin VCC # Yellow
  # Pin GND # Brown
  Pin_hx711_dout: "GPIO18"  # Red
  Pin_hx711_clk: "GPIO19"   # Orange
# Configuration Parameters
  # Format: substitutionID: "substitution" #Note
  # Example: humidity_setpoint_select_low: "65" #Lowest setpoint available in HA
###
### Custom Device Configuration ################################################
###
### Weight of reserve tank #########################################
# Logs approximate weight in lbs
sensor:
  - platform: hx711
    id: RO_lbs
    name: "RO Weight"
    dout_pin: ${Pin_hx711_dout}
    clk_pin: ${Pin_hx711_clk}
    gain: 128
    filters:
      - calibrate_linear:
          - 366120 -> 0  #old = 365700 then 363500 #negative?
          - 262322 -> 10 #new entry
          - 209445 -> 15 #old = 229050 then 213100
          - 156964 -> 20 #new entry
      - median:
          window_size: 15
          send_every: 5
          send_first_at: 1
      - delta: .1 # should only send data if there's a change of .1 lbs
    unit_of_measurement: lbs
    state_class: measurement
    accuracy_decimals: 1
    update_interval: 1s
### Enables/disables pump based on lbs #############################
### Automation for setting binary sensor
# Empty range = 8.3 (garunteed) to 8.5 (likely) lbs OLD
# Empty range = 7.0 (garunteed) to 7.5 (likely) lbs NEW CALIBRATION
### running false = < 7.6 lbs
# Typical refill = 5.3 (low) to 5.5 (higher) lbs
# Max refill seen = 11.3 lbs, assumes high pressure tank is empty
### running true = > 14.0
# Typical refill 5.5 + likely empty 7.5 = 13.0 lbs
    on_value:
      then:
      - if:
          condition:
            sensor.in_range:
              id: RO_lbs
              below: 7.7
          then:
            lambda: !lambda id(RO_reserve).publish_state(false);
      - if:
          condition:
            sensor.in_range:
              id: RO_lbs
              above: 13
          then:
            lambda: !lambda id(RO_reserve).publish_state(true);
#
### Sensor indictating RO Reserve ##################################
# HA uses this to enable/disable pump
binary_sensor:
  - platform: template
    name: "RO Has Reserve"
    id: RO_reserve
    device_class: running