################################################################################
### WARNING Core Configuration Settings: confirm before adoption ###############
esp32:
  board: esp32dev
  framework:
    type: esp-idf
### Device Template 2.0 ##################################################
packages:
  template: !include
    file: common/template.yaml
    vars:
### WARNING Template Substitutions: adjust during setup ########################
      devicename: "esphome-blank"       #used as mDNS name
      friendly_devicename: "ESP Blank"  #used in ESP Manager & HA Device
      device_namelabel: "blank"         #used in Entity labels as prefix
      device_ip_address: "10.0.20.666"    #must be DHCP reserved. For wifi settings changes / mDNS failures
# Connection roubleshooting: Remove commments to override template
#wifi:
#  use_address: ${devicename}.local
#  use_address: ${device_ip_address}
################################################################################
###
### Device Specific Substitutions: Adjust during setup
substitutions:
# Wiring Substitutions
  # Pin_VCC #Red, Yellow Thin
  # Pin_GND #Black x2
  Pin_substitutionID22: "GPIO22" #Wiring color
  # Example: Pin_DHT_sensor: "GPIO21" #Green
# Configuration Parameters
  # Format: substitutionID: "substitution" #Note
  # Example: humidity_setpoint_select_low: "65" #Lowest setpoint available in HA
###
### Custom Device Configuration ################################################
###
### Example sub heading ###################################
#
# Stuff here