################################################################################
### WARNING Core Configuration Settings: confirm before adoption ###############
esp32:
  board: esp32dev
  framework:
    type: esp-idf
### Core Template 2.0
packages:
  template: !include
    file: common/core-template.yaml
    vars:
### WARNING Template Substitutions: adjust during setup ########################
      devicename: "esphome-desk"       #used as mDNS name
      friendly_devicename: "ESP Desk"  #used in ESP Manager & HA Device
      device_ip_address: "10.0.20.45"  #must be DHCP reserved. For wifi settings changes / mDNS failures
### Troubleshooting wifi: Remove commments to override template
#wifi:
#  use_address: ${devicename}.local
#  use_address: ${device_ip_address} #set in Template Substitutions above
###
substitutions:
### WARNING Naming Substituion: Adjust during setup ############################
  device_namelabel: "Desk"
### END Core Template
################################################################################
###
### Device Specific Substitutions ##############################################
# Wiring Substitution
  # Pin_GND #Black
  Pin_LED_Counter: "GPIO17"     #white
  Pin_Warmer_Button: "GPIO16"   #white
###
### Custom Device Configuration ################################################
###
### WOL Triggers ###################################
# Used to reach devices sharing the VLAN with this ESP 
button:
  - platform: wake_on_lan
    name: "Wake LoungeTV"
    target_mac_address: b0:37:95:b8:bf:92
  - platform: wake_on_lan
    name: "Wake DenTV"
    target_mac_address: 64:95:6c:c5:ec:ca
  - platform: wake_on_lan
    name: "Wake BedroomTV"
    target_mac_address: 58:fd:b1:70:4f:d7
#
### Virutual Switch ###################################
# Turns desk warmer on/off at preset levels via virtual button presses
switch:
  - platform: template
    name: "Warmer"
    id: desk_warming_switch
    turn_on_action:  ## Turn on to 40c mode
      - switch.template.publish:
          id: desk_warming_switch
          state: ON
      - output.turn_on: warmer_button ## first press, hold 3 seconds
      - delay: 3000ms
      - output.turn_off: warmer_button ## release and wait
      - delay: 250ms
      - output.turn_on: warmer_button ## second press, short hold
      - delay: 250ms
      - output.turn_off: warmer_button ## release
    turn_off_action:
      - switch.template.publish:
          id: desk_warming_switch
          state: OFF
      - output.turn_on: warmer_button ## first press
      - delay: 3000ms                ## HOLD FOR 3 SECONDS
      - output.turn_off: warmer_button ## release
#
### State Detection ###################################
# Detects device on/off state based on LED refreshes
# Internal to ESP
sensor:
  - platform: pulse_counter
    id: led_counter
    pin: ${Pin_LED_Counter}
    internal: true
    update_interval: 10s
    on_value_range:
      - above: 13000 # actual reading typically over 14600 (untested on ESP-IDF framework)
        then:
        - switch.template.publish:
            id: desk_warming_switch
            state: OFF
      - below: 10000 # actual reading either 0 or about 7332 (untested on ESP-IDF framework)
        then:
        - switch.template.publish:
            id: desk_warming_switch
            state: ON
#
### Button Press ###################################
# Internal to ESP by default
output:
  - platform: gpio
    id: warmer_button
    pin:
      number: ${Pin_Warmer_Button}
      inverted: true