################################################################################
### WARNING Core Configuration Settings: confirm before adoption ###############
esp32:
  board: esp32dev
  framework:
    type: esp-idf
### Core Template 2.1
packages:
################################################################################
### Custome packagages NON TEMPLATE
### 
###   Control Components
###  # Humidor Set Points: HA configurable
  
###  # Humidor Climate Output: PWM Fan using LEDC
  climate_output: !include humidor-build/climate-output.yaml
###  # Humidor Climate Sensors: DHT22
  climate_sensors: !include humidor-build/climate-sensors.yaml
### Control states ----- (currently blank)
###  # the humidor will always be in one of three states. these can be built independently and modularized 
###  # 1: Running: PID Contoller      ****WIP****
###  # 2: Paused (Lid is Open): Automations
###  # 3: Stopped: (Error or mainenance state) Automations
###
################################################################################
  template: !include
    file: common/core-template.yaml
    vars:
### WARNING Template Substitutions: adjust during setup ########################
      devicename: "esphome-humidor"       #used as mDNS name
      friendly_devicename: "ESP Humidor"  #used in ESP Manager & HA Device
      device_ip_address: "10.0.20.252"    #must be DHCP reserved. For wifi settings changes / mDNS failures
### Troubleshooting wifi: Remove commments to override template
#wifi:
#  use_address: ${devicename}.local
#  use_address: ${device_ip_address} #set in Template Substitutions above
###
substitutions:
### WARNING Naming Substituion: Adjust during setup ############################
  device_namelabel: "Humidor"
### END Core Template
################################################################################
###
### Device Specific Substitutions ##############################################
# Wiring Substitutions
# Pin_VCC #Red, Yellow Thin
# Pin_GND #Black x2
  Pin_DHT_sensor: "GPIO21" #Green
  Pin_Fan_PWMinput: "GPIO17" #Blue Thin
  Pin_Fan_RPMoutput: "GPIO16" #Green Thin
# Configuration Parameters
  humidity_setpoint_select_low: "65" #Lowest setpoint available in HA
  humidity_setpoint_select_high: "75" #Highest setpoint available in HA
###
### Custom Device Configuration ################################################
###
### Humidor Set Points #############################################
# Accepts Home Assistant Input
#
####### NEEDS CLEANUP
#
number:
  - platform: template
    id: humidity_setpoint
    name: "Humidity Setpoint"
    optimistic: true
    initial_value: 70 # make variable?
    min_value: ${humidity_setpoint_select_low}
    max_value: ${humidity_setpoint_select_high}
    step: 0.1
    restore_value: True
#
#
###  Control State #1 Running: PID Contoller #######################################
# New home of the PID logic
#   Change to PID function: https://esphome.io/components/climate/pid
#
###  Control State #2 Paused #######################################
#
#
###  Control State #3 Stopped ######################################
#
# Fan running without humidity rising?
# Humidity below a threshold? Will opening trigger a false alarm?
# Stop running fan at full speed until refilled?
