### Device Basic Configuration ################################################
### Device Template 1.0
substitutions:
  devicename: "esphome-desk"
  friendly_devicename: "ESP Desk"
#these must be set correctly on adoption
esp32:
  board: esp32dev
  framework:
    type: arduino
###
### END
### Common ESPHome Device Configurations ################################################
### No or few changes should be needed
#
esphome:
  name: ${devicename}
  friendly_name: ${friendly_devicename}
  min_version: 2024.11.0
  name_add_mac_suffix: false
# Enable logging
logger:
# Enable Home Assistant API and encryption key
api:
  encryption: 
    key: !secret API_key
# Enable Over The Air updates with ESPhome
ota:
  platform: esphome
# Enable Wifi commented lines are for moving between networks
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  use_address: ${devicename}.local
#  use_address: 10.0.20.45
#
# Enable fallback hotspot & captive portal in case wifi connection fails >1 minute
  ap:
    ssid: ${devicename}
    password: !secret ESPadmin_password
captive_portal:

### Common Diagnostic Display Configuration ################################################
# Adds Diagnostics to HA
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_devicename}: IP"
      icon: "mdi:ip-outline"
    mac_address:
      name: "${friendly_devicename}: MAC"
      icon: "mdi:network-outline"
    ssid:
      name: "${friendly_devicename}: SSID"
      icon: "mdi:wifi-settings"      
### Moved to custom
#sensor:
#  - platform: wifi_signal
#    name: "${friendly_devicename}: WiFi Signal"
#    update_interval: 60s
# Restart & Safe Mode Buttons to HA
button:
  - platform: restart
    name: "Restart Device"
  - platform: safe_mode
    name: "Restart in Safe Mode"
### Custom Device Configuration ################################################
#WOL triggers
  - platform: wake_on_lan
    name: "Wake LoungeTV"
    target_mac_address: b0:37:95:b8:bf:92
  - platform: wake_on_lan
    name: "Wake DenTV"
    target_mac_address: 64:95:6c:c5:ec:ca
  - platform: wake_on_lan
    name: "Wake BedroomTV"
    target_mac_address: 58:fd:b1:70:4f:d7


switch:
  #Virtual switch to turn desk warmer on/off ###################################
  - platform: template
    name: "Warmer"
    id: desk_switch_template
    turn_on_action:  ## Turn on to 40c mode
      - switch.template.publish:
          id: desk_switch_template
          state: ON
      - output.turn_on: gpio_button ## first press, hold 3 seconds
      - delay: 3000ms
      - output.turn_off: gpio_button ## release and wait
      - delay: 250ms
      - output.turn_on: gpio_button ## second press, short hold
      - delay: 250ms
      - output.turn_off: gpio_button ## release
    turn_off_action:
      - switch.template.publish:
          id: desk_switch_template
          state: OFF
      - output.turn_on: gpio_button ## first press
      - delay: 3000ms                ## HOLD FOR 3 SECONDS
      - output.turn_off: gpio_button ## release

sensor:
### Moved from template
  - platform: wifi_signal
    name: "${friendly_devicename}: WiFi Signal"
    update_interval: 60s
  #Internal to ESP detect device on/off state and sync HA/ESP indicators #######
  - platform: pulse_counter
    pin: 17
    name: "Pulse Counter"
    internal: true
    update_interval: 10s
    on_value_range:
      - above: 13000 # actual reading typically over 14600
        then:
        - switch.template.publish:
            id: desk_switch_template
            state: OFF
      - below: 10000 # actual reading either 0 or about 7332
        then:
        - switch.template.publish:
            id: desk_switch_template
            state: ON

output:
  #Button touch, internal only to ESP ##########################################
  - platform: gpio
    id: gpio_button  
    pin:
      number: 16
      inverted: true