################################################################################
### WARNING Core Configuration Settings: confirm before adoption ###############
esp32:
  board: esp32dev
  framework:
    type: esp-idf
### Core Template 2.0
packages:
  template: !include
    file: common/core-template.yaml
    vars:
### WARNING Template Substitutions: adjust during setup ########################
      devicename: "esphome-humidor"       #used as mDNS name
      friendly_devicename: "ESP Humidor"  #used in ESP Manager & HA Device
      device_ip_address: "10.0.20.252"    #must be DHCP reserved. For wifi settings changes / mDNS failures
### Troubleshooting wifi: Remove commments to override template
#wifi:
#  use_address: ${devicename}.local
#  use_address: ${device_ip_address} #set in Template Substitutions above
###
substitutions:
### WARNING Naming Substituion: Adjust during setup ############################
  device_namelabel: "Humidor"
### END Core Template
################################################################################
###
### Device Specific Substitutions ##############################################
# Wiring Substitutions
# Pin_VCC #Red, Yellow Thin
# Pin_GND #Black x2
  Pin_DHT_sensor: "GPIO21" #Green
  Pin_Fan_PWMinput: "GPIO17" #Blue Thin
  Pin_Fan_RPMoutput: "GPIO16" #Green Thin
# Configuration Parameters
  humidity_setpoint_select_low: "65" #Lowest setpoint available in HA
  humidity_setpoint_select_high: "75" #Highest setpoint available in HA
###
### Custom Device Configuration ################################################
###
### Configutation Outline
###
### Control Components
###  # Humidor Set Points
###  # Humidor Climate Sensors
###  # Humidor Climate Output: PWM Fan using LEDC
### Control states
###  # the humidor will always be in one of three states. these can be built independently and modularized 
###  # 1: Running: PID Contoller
###  # 2: Paused (Lid is Open): Automations
###  # 3: Stopped: (Error or mainenance state) Automations
###
### END Outline
#
### Humidor Set Points #############################################
# Accepts Home Assistant Input
#
####### NEEDS CLEANUP
#
number:
  - platform: template
    id: humidity_setpoint
    name: "Humidity Setpoint"
    optimistic: true   #### not sure this is correct
    initial_value: 70 # make variable?
    min_value: ${humidity_setpoint_select_low}
    max_value: ${humidity_setpoint_select_high}
    step: 0.1
    restore_value: True
# Stores the template number in a global as Float. Unclear if / why is this is needed. 
# added when attempting to dynmacally control the fan switch automation. won't be needed with PID
    on_value:
      then:
        - lambda: |-
            id(global_humidity_setpoint) = float(x);
# delete this?
# seems like this 
globals:
  - id: global_humidity_setpoint
    type: float
    restore_value: True
    initial_value: '70'
#
### Humidor Climate Sensors ########################################
#
####### NEEDS CLEANUP
#
sensor:
  - platform: dht
    pin: "${Pin_DHT_sensor}"
    temperature:
      name: "${device_namelabel} Temperature"
    humidity:
      name: "${device_namelabel} Humidity"
      id: humidity
# Contains current fan automations. Refactor this into PID Controller
# Enhancements to abandon:
#   Add HA controllable set point
#   Tweak +-Deadband to better fit with sensor specs, at least 1 degree 
#   Global default fan to off?
#   Add initial power on update followed by less frequent intervals?
      on_value_range:
#        - above: global_humidity_setpoint ##this is a big test!
#        - above: !lambda "global_humidity_setpoint;" ##this is a big test!
        - above: 70.1
          then:
            - switch.turn_off:
                id: humidor_fan
        - below: 68.9
          then:
            - switch.turn_on:
                id: humidor_fan
    update_interval: 15s
#
### Climate Output: PWM Fan using LEDC ###################################
#
# NOTE: currently binary on/off swtich.
switch:
  - platform: gpio
    pin: "${Pin_Fan_PWMinput}"
    id: humidor_fan
    name: "${device_namelabel} Fan Power"
#
# DRAFT: Fan platform to use PWM for speed control. Replaces switch above, requires modifing DHT automation
#
# Pin 17 - Blue Thin - Fan PWM input
#output:
#  - platform: ledc
#    pin: "${Pin_Fan_PWMinput}"
#    frequency: 10000 Hz
#    id: humidor_fan_pwm
#fan:
#  - platform: speed
#    output: humidor_fan_pwm
#    name: "${device_namelabel} Fan PWM"
#
#### DRAFT: Monitor fan RPM. Is this meaningfully different from PWM setting other than troubleshooting?
# Pin 16 - Green Thin - Fan RPM output
# Use pulse counter?
#
# Whitepaper note to convert to Hertz to RPM:
#   Tachometer output signal is in Hertz (= per second)
#   The fan sends two impulses per revolution
#   Fan speeds are usually in RPM (= per minute)
#   Formula: RPM = herz (per second) / 2 pulses * 60 seconds
#  If using a pulsecounter can it just be diveded by 2?
#
#
###  Control State #1 Running: PID Contoller #######################################
# New home of the PID logic
#   Change to PID function: https://esphome.io/components/climate/pid
#
###  Control State #2 Paused #######################################
#
#
###  Control State #3 Stopped ######################################
#
# Fan running without humidity rising?
# Humidity below a threshold? Will opening trigger a false alarm?
# Stop running fan at full speed until refilled?
